#!/usr/bin/env bash
# Materialise app/.env from the current environment so the appbook reads the SAME config the
# notebook does.
#
# Why this exists: the notebook runs in the VS Code server / an interactive shell, which inherits
# the OCI + Oracle env (forwarded by docker-compose from the Codespaces secrets). The appbook,
# however, is launched by the `postStartCommand` lifecycle hook — a non-interactive shell that does
# not always inherit those values, so its OCI calls failed (502 / "api key not readable"). Writing a
# real app/.env (which backend/config.py loads via python-dotenv) makes the appbook's config
# deterministic and identical to the notebook's, and it survives manual `./run.sh` restarts too.
#
# Only non-empty values are written, so we never clobber backend/config.py's sensible defaults with
# blanks. app/.env is git-ignored (it holds the API key) and is regenerated on every container start.
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/app/.env"
TMP="$ENV_FILE.tmp"

# Every var the notebook reads from the environment (workshop_setup.py / oci_key_rotation.py) that the
# appbook also needs (backend/config.py). Secrets + endpoints + model ids + Oracle connection.
VARS=(
  OCI_GENAI_API_KEY OCI_GENAI_API_KEY_2 OCI_GENAI_API_KEY_3 OCI_GENAI_API_KEY_4
  OCI_GENAI_ENDPOINT LLM_PROVIDER LLM_MODEL OPENAI_API_KEY
  ORA_DSN ORA_AGENT_USER ORA_AGENT_PWD ORACLE_ENABLED
  EMBED_MODEL RERANK_MODEL VECTOR_DIM
)

{
  echo "# Generated by scripts/write_app_env.sh — do not edit by hand (regenerated on container start)."
  echo "# Mirrors the environment the notebook uses so the appbook runs against the same harness."
  for name in "${VARS[@]}"; do
    val="${!name:-}"
    [ -n "$val" ] && printf '%s=%s\n' "$name" "$val"
  done
} > "$TMP"

mv "$TMP" "$ENV_FILE"

if grep -q '^OCI_GENAI_API_KEY=' "$ENV_FILE" 2>/dev/null; then
  n=$(grep -c '^OCI_GENAI_API_KEY' "$ENV_FILE")
  echo "▸ Wrote app/.env (${n} OCI key(s) present)."
else
  echo "⚠ Wrote app/.env, but no OCI_GENAI_API_KEY was found in the environment."
  echo "  Set it as a Codespaces secret (org-level recommended) and rebuild the container,"
  echo "  or for a local run put it in app/.env directly. The appbook serves but chat will 502."
fi
